### ISSUE TITLE
babel with es2015-rollup is broken

### ISSUE THREAD

**Issue by nowamasa** [yamafaktory/babel-react-rollup-starter#2]
This is what I see when I try to build it

> It looks like your Babel configuration specifies a module transformer. Please disable it. If you're using the "es2015" preset, consider using "es2015-rollup" instead.

I am using:
- node v5.2.0
- npm v3.3.12
- Windows 10

**Comment by yamafaktory** [comment]
Hi @nowamasa,

It could be very likely that your issue is a Windows specific one, please take a look at https://github.com/rollup/babel-preset-es2015-rollup/issues/11.

One solution for you could potentially be to replace the following section in the `config/dev.js` file as follow:

``` js
presets: [ 'es2015', 'stage-0', 'react', { modules: false } ]
```

I'm going to update the project with more up-to-date dependencies.

**Comment by nowamasa** [comment]
Hi @yamafaktory,
Yep, it is a Windows specific issue.

When I use `{ modules: false }` I see a new error:

> Using removed Babel 5 option: foreign.modules - Use the corresponding module transform plugin in the `plugins` option.

I am will try to fix it later today.

**Comment by yamafaktory** [comment]
@nowamasa maybe adding `external-helpers` as follow will help: https://github.com/rollup/babel-preset-es2015-rollup/issues/11#issuecomment-238709022

**Comment by callahanchris** [comment]
@nowamasa I recently came across a similar issue (though not on Windows) on a project loosely based on this repo. It worked after changing the `config/dev.js` file to the following:

``` diff
babel({
  babelrc: false,
  exclude: 'node_modules/**',
-  presets: [ 'es2015-rollup', 'stage-0', 'react' ]
+  presets: [ [ 'es2015', { modules: false } ], 'stage-0', 'react' ],
+  plugins: [ 'external-helpers' ]
}),
```

@yamafaktory would you accept a PR making this change and updating the project's dependencies accordingly?

**Comment by yamafaktory** [comment]
@callahanchris I'll thankfully accept a PR from you, especially if this is not Windows-centric!

**Comment by nowamasa** [comment]
thanks @callahanchris, it works with that change.

@yamafaktory feel free to close this issue after you accept that PR.

**Comment by yamafaktory** [comment]
@nowamasa Great news!
