### ISSUE TITLE
Documentation for usage is lacking

### ISSUE THREAD

**Issue by mwozniczak** [yamafaktory/babel-react-rollup-starter#27]
Documentation for what to do right after the installation is missing. What do I do with this? Do I copy the contents over from the npm dir (since Installation section wants me to install it `--global`ly)? If so, do I copy the _whole_ thing over, or just part of it? Which part?

**Comment by yamafaktory** [comment]
Hi @mwozniczak,

You're right, first of all installing it globally is absolutely not needed and was done in this [PR](https://github.com/yamafaktory/babel-react-rollup-starter/pull/1). You can simply perform a `npm i babel-react-rollup-starter` in a fresh directory to start a new project and then please refer to the [usage section](https://github.com/yamafaktory/babel-react-rollup-starter#usage).

You can also simply perform a `git clone https://github.com/yamafaktory/babel-react-rollup-starter.git` and `cd` into that directory.

I'll update the documentation to make it more obvious, thanks for the feedback!
