### ISSUE TITLE
Use rollup-watch for incremental builds

### ISSUE THREAD

**Issue by ngryman** [yamafaktory/babel-react-rollup-starter#54]
Hey,

Thanks for this simple well done boilerplate.

I would use `rollup --watch` instead of `onchange` in order to leverage incremental builds proposed by `rollup-watch`: https://github.com/rollup/rollup-watch.

**Comment by yamafaktory** [comment]
Hi @ngryman,

Thanks a lot for the hint, this totally makes sense. When I created this boilerplate, I don't think I heard about 'rollup-watch` (or I simply missed it). Feel free to open a PR or I will do it when have some free time.

**Comment by yamafaktory** [comment]
@ngryman done in https://github.com/yamafaktory/babel-react-rollup-starter/releases/tag/v4.0.0, thanks again 👍. Everything should be fine, please test it and close this issue.

**Comment by yamafaktory** [comment]
Oh, I forgot to remove the `build:dev` step for Travis... will do it in a new patch version.

**Comment by ngryman** [comment]
@yamafaktory Awesome thanks 🍻
