### ISSUE TITLE
broswser-sync --index option invalid

### ISSUE THREAD

**Issue by Amorites** [yamafaktory/babel-react-rollup-starter#70]
In browser (Chrome http://localhost:3000/) I see only : Cannot GET/

- WIN7
- browser-sync 2.18.12

change
```
    "browse": "browser-sync start --s --index 'html/index-dev.html' --files 'html/**/*.html, build/**/*.js' --no-notify",
```
to
```
    "browse": "browser-sync start --s --index html/index-dev.html --files 'html/**/*.html, build/**/*.js' --no-notify",
```

solve the problem

**Comment by yamafaktory** [comment]
Hi @Amorites,

Thank you for the report! This is very likely related to your environment (i.e. Windows). I'll fix it.

**Comment by yamafaktory** [comment]
This is fixed now in the latest version https://github.com/yamafaktory/babel-react-rollup-starter/releases/tag/v5.1.0.
