### ISSUE TITLE
Latest React 16 conflicts with rollup-plugin-commonjs

### ISSUE THREAD

**Issue by yamafaktory** [yamafaktory/babel-react-rollup-starter#90]
A fix is already in the pipeline and awaiting a new release https://github.com/rollup/rollup-plugin-commonjs/pull/233 🚀.

**Comment by kiddyfurby** [comment]
please update yarn.lock so that version 8.2.4 of rollup-plugin-commonjs is used

**Comment by yamafaktory** [comment]
Sorry for the late reply. This has been fixed in the latest version https://github.com/yamafaktory/babel-react-rollup-starter/releases/tag/v7.0.0.
